<?php

require_once 'ConsumerBaseTest.php';

/**
 * Class ConsumerOrderSubmitTest
 *
 * tested endpoint:
 * // Get Order Status rows
 * '/order/submit/a/:apikey/e/:epoch/u/:sessionToken'
 */
class ConsumerOrderConfirmSlackTest extends ConsumerBaseTest
{
    /**
     *
     */
    public function testSubmitOrder()
    {
        $user = $this->createUser();

        // Kraze Burgers
        $payload = 'YToxOntzOjc6InBheWxvYWQiO3M6MTk4ODoieyJhY3Rpb25zIjpbeyJuYW1lIjoiY29uZmlybV9hY3Rpb24iLCJ0eXBlIjoiYnV0dG9uIiwidmFsdWUiOiIxIn1dLCJjYWxsYmFja19pZCI6ImNvbmZpcm1fb3JkZXJfXzEyMzQ1NiIsInRlYW0iOnsiaWQiOiJUMDUxTlE3S0UiLCJkb21haW4iOiJhaXJwb3J0c2hlcnBhIn0sImNoYW5uZWwiOnsiaWQiOiJDNDNKWTFOSkQiLCJuYW1lIjoiX3Rlc3RfY29uZmlnIn0sInVzZXIiOnsiaWQiOiJVMDUxVEdIVEUiLCJuYW1lIjoibWF5YW5rIn0sImFjdGlvbl90cyI6IjE0ODY5MjU5MzIuNzM3MzI4IiwibWVzc2FnZV90cyI6IjE0ODY5MjU5MjYuMDAwMDk1IiwiYXR0YWNobWVudF9pZCI6IjEiLCJ0b2tlbiI6IlNEMjRsMXhFc2lkbkVuVDBvQlJ3UXRaeSIsIm9yaWdpbmFsX21lc3NhZ2UiOnsidGV4dCI6IlgiLCJib3RfaWQiOiJCNDNNTEFLRlQiLCJhdHRhY2htZW50cyI6W3siY2FsbGJhY2tfaWQiOiJjb25maXJtX29yZGVyX18xMjM0NTYiLCJ0ZXh0IjoiYFJlc3BvbnNlIHJlcXVpcmVkYCIsInByZXRleHQiOiJPcmRlciMgMTIzNDUiLCJpZCI6MSwidHMiOjE0ODY4NjQ1MDQsImNvbG9yIjoiMzZhNjRmIiwiZmllbGRzIjpbeyJ0aXRsZSI6IiIsInZhbHVlIjoiKkRlbGl2ZXJ5IE9yZGVyKiIsInNob3J0IjpmYWxzZX0seyJ0aXRsZSI6Ii0tLSIsInZhbHVlIjoiIiwic2hvcnQiOmZhbHNlfSx7InRpdGxlIjoiT3JkZXIgRGF0ZSAmYW1wOyB0aW1lIiwidmFsdWUiOiJGZWItMTEsIDEyOjMwIFBNIiwic2hvcnQiOnRydWV9LHsidGl0bGUiOiJNdXN0IHByZXBhcmUgYnkiLCJ2YWx1ZSI6ImAxOjI1IFBNYCIsInNob3J0Ijp0cnVlfSx7InRpdGxlIjoiTnVtYmVyIG9mIEl0ZW1zIiwidmFsdWUiOiI4Iiwic2hvcnQiOnRydWV9LHsidGl0bGUiOiJDdXN0b21lciIsInZhbHVlIjoiTWF5YW5rIEdhbmRoaSIsInNob3J0Ijp0cnVlfSx7InRpdGxlIjoiLS0tIiwidmFsdWUiOiIiLCJzaG9ydCI6ZmFsc2V9LHsidGl0bGUiOiJJdGVtKHMpIiwidmFsdWUiOiJDaGlja2VuIGJ1cmdlclxuKisqIFNhbGFkXG5gU3BlY2lhbCBJbnN0cnVjdGlvbnNgOiBObyBEYWlyeSIsInNob3J0Ijp0cnVlfSx7InRpdGxlIjoiUXR5IiwidmFsdWUiOiIxIiwic2hvcnQiOnRydWV9LHsidGl0bGUiOiItLS0iLCJ2YWx1ZSI6Ik1haGFyYWphIGJ1cmdlciIsInNob3J0Ijp0cnVlfSx7InRpdGxlIjoiLS0tIiwidmFsdWUiOiIyIiwic2hvcnQiOnRydWV9LHsidGl0bGUiOiItLS0iLCJ2YWx1ZSI6IlNvbWV0aGluZyBlbHNlIGJ1cmdlciIsInNob3J0Ijp0cnVlfSx7InRpdGxlIjoiLS0tIiwidmFsdWUiOiIxIiwic2hvcnQiOnRydWV9LHsidGl0bGUiOiItLS0iLCJ2YWx1ZSI6IlR1bmEgYnVyZ2VyIiwic2hvcnQiOnRydWV9LHsidGl0bGUiOiItLS0iLCJ2YWx1ZSI6IjMiLCJzaG9ydCI6dHJ1ZX1dLCJhY3Rpb25zIjpbeyJpZCI6IjEiLCJuYW1lIjoiY29uZmlybV9hY3Rpb24iLCJ0ZXh0IjoiQWNjZXB0IiwidHlwZSI6ImJ1dHRvbiIsInZhbHVlIjoiMSIsInN0eWxlIjoicHJpbWFyeSJ9LHsiaWQiOiIyIiwibmFtZSI6ImNvbmZpcm1fYWN0aW9uIiwidGV4dCI6IlJlamVjdCIsInR5cGUiOiJidXR0b24iLCJ2YWx1ZSI6Ii0xIiwic3R5bGUiOiJkYW5nZXIiLCJjb25maXJtIjp7InRleHQiOiJPbmNlIHRoZSBvcmRlciBpcyByZWplY3RlZCwgaXQgY2Fubm90IGJlIHJlcHJvY2Vzc2VkLiIsInRpdGxlIjoiQXJlIHlvdSBzdXJlPyIsIm9rX3RleHQiOiJZZXMiLCJkaXNtaXNzX3RleHQiOiJOdmVybWluZCJ9fV0sIm1ya2R3bl9pbiI6WyJ0ZXh0IiwicHJldGV4dCIsImZpZWxkcyJdLCJmYWxsYmFjayI6Ik5PIEZBTExCQUNLIERFRklORUQifV0sInR5cGUiOiJtZXNzYWdlIiwic3VidHlwZSI6ImJvdF9tZXNzYWdlIiwidHMiOiIxNDg2OTI1OTI2LjAwMDA5NSJ9LCJyZXNwb25zZV91cmwiOiJodHRwczpcL1wvaG9va3Muc2xhY2suY29tXC9hY3Rpb25zXC9UMDUxTlE3S0VcLzE0MTA5NDAwMzA3OFwvb0JucW1KVmk5S3BsdGo5YXJxQzBwZGlBIn0iO30=';


        $url = $this->generatePath('order/confirm/slack', $user->getSessionToken(), "");

        $response = $this->post($url, [
            'payload' => $payload,
        ]);

        $jsonDecodedBody = $response->getJsonDecodedBody();

        var_dump($jsonDecodedBody);
    }


}