<?php
return [
    'angularWebUrl' => '',
    'wordpressWebUrl' => '',
    'WebsiteUpUrl' => '',
    'WebsiteUpApiKey' => '',
    'WebsiteUpExptectedResultRawBody' => '',
    'WebsiteUpExptectedResultCode' => 200,
    'slackStatusWebhookUrl' => '',
    'slackErrorWebhookUrl' => '',
    'queueConditionGoodMaxMessages' => '',
    'queueConditionStableMaxMessages' => '',
    'queueMidPriorityConditionGoodMaxMessages' => '',
    'queueMidPriorityConditionStableMaxMessages' => '',
    'queueDeadLetterConditionGoodMaxMessages' => '',
    'queueDeadLetterConditionStableMaxMessages' => '',
    'parseConditionGoodMaxConnectTime' => '',
    'parseConditionStableMaxConnectTime' => '',
    'queueConfig' => '',
    'queueQueueName' => '',
    'queueMidPriorityConfig' => '',
    'queueMidPriorityQueueName' => '',
    'queueDeadLetterConfig' => '',
    'queueDeadLetterQueueName' => '',
    'twilioPhoneNumbers' => '',
    'twilioInformNotMoreOftenThenXMin' => '',
    'twilioSID' => '',
    'twilioToken' => '',
    'twilioFromPhoneNumber' => '',
    'appEnvironment' => '',
    'configParseServerURL' => '',
    'configParseMount' => '',
    'configParseApplicationId' => '',
    'configParseRestAPIKey' => '',
    'configParseMasterKey' => '',

];
